### ISSUE TITLE
Design test support

### ISSUE THREAD

**Issue by ns-cweber** [weberc2/builder#5]
Some prompt questions for the design:

- [x] Where should tests be in the dependency tree?
    * Following the bazel/pants/etc example seems prudent; the Nix example has been more difficult to manage in my experience with both Nix and Pants
- [x] Do we have a separate verb for running tests?
    * I don't see this being necessary; the target type _is_ the verb
- [x] Are tests built into pexes?
    * Solved by running tests in a virtualenv
- [x] How do we manage the pytest dependency?
    * Solved by making a pytest target (on the macros/python package) that is a dependency of all py_test target types
- [ ] Create example

**Comment by weberc2** [comment]
The example will be covered by #29
